### ISSUE TITLE
Create question/lecture association

### ISSUE THREAD

**Issue by hurtfulthings** [JDTeamAcetabulum/qna#63]

**Comment by strburst** [comment]
@hurtfulthings you should flesh out this issue a bit more! Do the following:
- Describe what this issue is about
- Move to In Progress if this is In Progress or Backlog if we're going to do it soon
- Assign yourself if you plan to do this
- Assign it to this sprint if it should be done this sprint
- Give a story point estimate
- Is this associated with a user story? If so, assign it to the appropriate epic.

**Comment by strburst** [comment]
Closed by #85.
